export const communitySection = `<section class="page" data-page="community">
          <div class="community-shell">
            <header class="community-header"><div><h1>Community ✨</h1><p>在这里，分享治愈，收获力量，一起慢慢变好 💜</p></div><div class="community-actions"><button class="community-compose">✎　发布动态</button><span>♧</span><img src="./assets/shared-brand/brand-avatar-tile.png" alt=""></div></header>
            <div class="community-layout">
              <main class="community-main">
                <section class="community-hero"><h2>你并不孤单，我们都在努力生长 ✨</h2><p>分享你的故事，互相鼓励，成为彼此的光 🌈</p><div class="community-hero-buttons"><button>✎　分享我的故事</button><button>#　浏览话题</button></div></section>
                <div class="community-tabs tabs" id="communityTabs"><button class="active">关注</button><button>最新</button><button>热门</button><button>精华</button><select><option>全部动态</option></select></div>
                <section class="community-feed" id="posts">
                  <article class="community-post community-glass"><img class="community-post-avatar" src="./league-avatars/luna.png" alt=""><div class="community-post-copy"><h3>小蒲公英 <small>Lv.6</small></h3><p>今天终于连续打卡第 7 天啦！虽然掉发还是有，但头皮状态明显舒服多了～<br>坚持护理真的会有改变，相信时间！🌱</p><span class="community-tag"># 连续打卡</span></div><div class="community-media"><img src="./assets/diary/diary-sunset-hero.jpg" alt=""></div><div class="community-post-actions"><span><img src="./assets/community/icons/heart.svg" alt="">128</span><span><img src="./assets/community/icons/comment.svg" alt="">36</span><span><img src="./assets/community/icons/bookmark.svg" alt="">收藏</span></div></article>
                  <article class="community-post community-glass"><img class="community-post-avatar" src="./league-avatars/bella.png" alt=""><div class="community-post-copy"><h3>爱吃草莓 <small>Lv.4　 昨天 21:35</small></h3><p>分享一个我最近超喜欢的头皮按摩方法！每天睡前按 5 分钟，放松又助眠 😊<br>推荐给大家试试～</p><span class="community-tag"># 头皮护理</span></div><div class="community-post-actions"><span><img src="./assets/community/icons/heart.svg" alt="">96</span><span><img src="./assets/community/icons/comment.svg" alt="">38</span><span><img src="./assets/community/icons/bookmark.svg" alt="">收藏</span></div></article>
                  <article class="community-post community-glass"><img class="community-post-avatar" src="./league-avatars/mia.png" alt=""><div class="community-post-copy"><h3>薄荷味的风 <small>Lv.6　 昨天 18:20</small></h3><p>最近压力有点大，掉发也跟着严重了…深呼吸、运动、喝水，给自己一些温柔的时间 🍀</p><span class="community-tag"># 情绪管理</span></div><div class="community-post-actions"><span><img src="./assets/community/icons/heart.svg" alt="">76</span><span><img src="./assets/community/icons/comment.svg" alt="">22</span><span><img src="./assets/community/icons/bookmark.svg" alt="">收藏</span></div></article>
                  <article class="community-post community-glass"><img class="community-post-avatar" src="./league-avatars/sophia.png" alt=""><div class="community-post-copy"><h3>向日葵 <small>Lv.3　 05-18</small></h3><p>新发型解锁啦！看着宝宝一点点成长出来的碎发，成就感满满！💪</p><span class="community-tag"># 新发型解锁</span></div><div class="community-media"><img src="./assets/buddy/hairstyles/dandelion.png" alt=""><img src="./assets/buddy/hairstyles/blue-bob.png" alt=""><img src="./assets/buddy/hairstyles/ribbon.png" alt=""></div><div class="community-post-actions"><span><img src="./assets/community/icons/heart.svg" alt="">143</span><span><img src="./assets/community/icons/comment.svg" alt="">42</span><span><img src="./assets/community/icons/bookmark.svg" alt="">收藏</span></div></article>
                </section>
              </main>
              <aside class="community-rail">
                <section class="community-glass community-rail-card hot-topics"><h2>热门话题 <small>更多 ›</small></h2><div class="topic-list"><div class="topic-row"><img src="./assets/community/icons/hashtag.svg" alt=""><b>连续打卡挑战</b><small>12.4k 讨论</small></div><div class="topic-row"><img src="./assets/community/icons/hashtag.svg" alt=""><b>头皮护理分享</b><small>8.7k 讨论</small></div><div class="topic-row"><img src="./assets/community/icons/hashtag.svg" alt=""><b>情绪管理小贴士</b><small>6.1k 讨论</small></div><div class="topic-row"><img src="./assets/community/icons/hashtag.svg" alt=""><b>新发型解锁</b><small>5.3k 讨论</small></div><div class="topic-row"><img src="./assets/community/icons/hashtag.svg" alt=""><b>健康饮食打卡</b><small>4.8k 讨论</small></div></div></section>
                <section class="community-glass community-rail-card community-event"><h2>社区活动 <small>更多 ›</small></h2><div class="event-body"><div class="event-calendar">21<br><small>DAYS</small></div><div class="event-copy"><b>21 天头皮养护打卡挑战</b><small>一起养成好习惯，赢取限定奖励！</small><small>05/20 – 06/09</small></div><button class="join-now">立即参加</button></div></section>
                <section class="community-glass community-rail-card recommended-groups"><h2>推荐小组 <small>更多 ›</small></h2><div class="group-list"><div class="group-row"><img src="./assets/buddy/hairstyles/blue-bob.png" alt=""><div><b>佛系养发小分队</b><small>成员 3,128</small></div><button>加入</button></div><div class="group-row"><img src="./assets/buddy/hairstyles/blue-bob.png" alt=""><div><b>运动养发日记</b><small>成员 2,856</small></div><button>加入</button></div><div class="group-row"><img src="./assets/buddy/hairstyles/dandelion.png" alt=""><div><b>饮食养发研究所</b><small>成员 2,341</small></div><button>加入</button></div><div class="group-row"><img src="./assets/buddy/hairstyles/ribbon.png" alt=""><div><b>熬夜星人互助会</b><small>成员 1,987</small></div><button>加入</button></div></div></section>
                <section class="community-glass community-rail-card active-stars"><h2>本周活跃之星 <small>更多 ›</small></h2><div class="star-grid"><div class="winner"><img src="./assets/shared-brand/brand-avatar-tile.png" alt=""><b>小蒲公英</b><small>1,250 XP</small></div><div><img src="./assets/buddy/hairstyles/blue-bob.png" alt=""><b>爱吃草莓</b><small>980 XP</small></div><div><img src="./assets/buddy/hairstyles/ribbon.png" alt=""><b>向日葵</b><small>860 XP</small></div><div><img src="./assets/buddy/hairstyles/dandelion.png" alt=""><b>薄荷味的风</b><small>720 XP</small></div><div><img src="./assets/buddy/hairstyles/blue-bob.png" alt=""><b>星星点点</b><small>640 XP</small></div></div></section>
              </aside>
            </div>
          </div>
        </section>`
